### ISSUE TITLE
Designables Build Fails in Xcode8

### ISSUE THREAD

**Issue by liu044100** [JakeLin/IBCalculator#1]
在Xcode8下面打开这个project的storyboard，出现`Designables Build Fails`的错误，也没法实时在storyboard上面调整设计。

请问下有没有解决办法

<img width="664" alt="2016-12-06 10 52 32" src="https://cloud.githubusercontent.com/assets/3689476/20910004/47f70dcc-bba2-11e6-8f23-30f3912e4ebe.png">

<img width="596" alt="2016-12-06 10 53 26" src="https://cloud.githubusercontent.com/assets/3689476/20910035/7965d82a-bba2-11e6-85c9-034650457d0b.png">

**Comment by JakeLin** [comment]
因为这个项目没有更新到 Swift 3.0 所以出问题，要解决这个问题，首先要更新到 3.0. 如果你愿意尝试，麻烦提交一个 PR， 谢谢！

**Comment by liu044100** [comment]
@JakeLin 升级到Swift 3.0 后问题解决了，提交了一个升级到3.0的PR。https://github.com/JakeLin/IBCalculator/pull/2
